/**
 * Shared director pipeline (script + MV modes).
 */

export {
  SCHEMA_VERSION,
  SCRIPT_NODE_TYPE,
  DIRECTOR_NODE_TYPE,
  DIRECTOR_SHOT_COLUMNS,
  DIRECTOR_MV_ASPECT_OPTIONS,
  createEmptyDirectorShot,
  isBlankDirectorShot,
  createEmptyDirectorAsset,
  createEmptyDirectorAssets,
  createEmptyDirectorShotStoryboard,
  createEmptyDirectorMvMusic,
  createEmptyDirectorMvStoryAnalysis,
  createEmptyDirectorMvScriptSections,
  createEmptyDirectorMvCastPlan,
  createDefaultDirectorPipelineState,
  flattenDirectorAssets,
  findDirectorAssetById,
  countAssetsMissingImages,
  countAssetsWithImages,
  countShotsWithFinalPrompt,
  countDirectorStoryboards,
  countDirectorShotsWithDialogue,
  getDirectorShotStoryboard,
  normalizeDirectorStoryboardsByShotNo,
  getValidDirectorShotSongClipUrl,
  recommendDirectorShotLipsync,
  resolveDirectorShotPreferLipsync,
  evaluateDirectorShotLipsync,
  shotDescriptionSuggestsVisibleFace,
  shotDescriptionSuggestsCloseUpFace,
  shotHasCompleteLyricForLipsync,
  shotSuggestsClimax,
  computeDirectorShotMusicRanges,
  computeDirectorShotMusicRangesFromState,
  findDirectorShotRowIndex,
  resolveDirectorShotMusicRange,
  applyLyricPacksToDirectorShots,
  syncDirectorShotsToLyricTimeline,
  parseLrcToLyricSegments,
  normalizeDirectorMvLyricSegments,
  coverSongWithLyricSegments,
  calibrateLyricSegmentsWithUserLyrics,
  splitUserLyricLines,
  packLyricSegmentsIntoShotPacks,
  pickNearestMvClipDurationTier,
  DIRECTOR_MV_CLIP_DURATION_TIERS,
  DIRECTOR_MV_CLIP_DURATION_TIERS_LONG,
  DIRECTOR_MV_CLIP_DURATION_TIERS_SHORT,
  resolveMvClipDurationTiers,
  shotMusicRangesFromLyricPacks,
  shotAudioRangeHasHumanVoice,
  classifyDirectorMvPackAudioRole,
  directorMvPackAudioRoleLabelZh,
  isDirectorLyricShotPackInstrumental,
  applyDirectorInstrumentalVisualGuards,
  stripDirectorSingingPerformanceFromText,
  DIRECTOR_INSTRUMENTAL_NO_SING_GUARD,
  isDirectorInstrumentalLyricText,
  sanitizeDirectorLyricDisplayText,
  isDirectorNonLyricMetaText,
  stripDirectorLyricsScriptMeta,
  breakDirectorLyricTextIntoLines,
  formatDirectorLyricsFromAsr,
  coerceDirectorMvAspectRatio,
  normalizeDirectorMvMusic,
  normalizeDirectorMvStoryAnalysis,
  normalizeDirectorMvScriptSections,
  normalizeDirectorMvCastPlan,
  parseDirectorMvScriptSectionsFromText,
  parseDirectorMvCharacterEntries,
  getDirectorMvCharactersSectionText,
  syncDirectorMvCastFromScript,
  ensureDirectorMvLeadSlots,
  applyDirectorMvCastPlan,
  formatDirectorMvLockedCastForPrompt,
  directorMvLeadGenderLabelZh,
  parseDirectorMvSceneEntries,
  getDirectorMvScenesSectionText,
  syncDirectorMvScenesFromScript,
  directorMvScriptSectionsHaveContent,
  composeDirectorMvScriptText,
  parseDirectorShotDurationSec,
  normalizeDirectorMode,
  normalizeDirectorPhase,
  normalizeDirectorImageResolution,
  type DirectorMode,
  type DirectorPhase,
  type DirectorAssetsStep,
  type DirectorShotColumnKey,
  type DirectorShot,
  type DirectorAssetKind,
  type DirectorAssetStatus,
  type DirectorAsset,
  type DirectorAssetsBag,
  type DirectorPipelineState,
  type DirectorShotStoryboard,
  type DirectorShotMusicRange,
  type DirectorStoryboardStatus,
  type DirectorMvMusic,
  type DirectorMvLyricSegment,
  type DirectorMvLyricSegmentStatus,
  type DirectorLyricShotPack,
  type DirectorMvPackAudioRole,
  type DirectorMvStoryAnalysis,
  type DirectorMvScriptSections,
  type DirectorMvCharacterEntry,
  type DirectorMvCastPlan,
  type DirectorMvLeadGender,
  type DirectorAssetGender,
  type DirectorMvAspectRatio,
  type SyncDirectorMvCastMode,
  type DirectorLipsyncPriority,
  type DirectorLipsyncRecommendation,
} from './schema.js';

export {
  DIRECTOR_SHOTS_SYSTEM_PROMPT,
  DIRECTOR_SHOTS_USER_PROMPT_TEMPLATE,
  DIRECTOR_MV_SHOTS_SYSTEM_PROMPT,
  DIRECTOR_MV_SHOTS_USER_PROMPT_TEMPLATE,
  DIRECTOR_MV_STORY_ANALYZE_SYSTEM_PROMPT,
  DIRECTOR_MV_STORY_ANALYZE_USER_PROMPT_TEMPLATE,
  DIRECTOR_MV_SCRIPT_SYSTEM_PROMPT,
  DIRECTOR_MV_SCRIPT_USER_PROMPT_TEMPLATE,
  DIRECTOR_ASSETS_SYSTEM_PROMPT,
  DIRECTOR_ASSETS_USER_PROMPT_TEMPLATE,
  DIRECTOR_PROMPTS_SYSTEM_PROMPT,
  DIRECTOR_PROMPTS_USER_PROMPT_TEMPLATE,
} from './prompts.js';

export {
  fillTemplate,
  buildDirectorShotsMessages,
  buildDirectorMvShotsMessages,
  buildDirectorMvStoryAnalyzeMessages,
  buildDirectorMvScriptMessages,
  buildDirectorAssetsMessages,
  buildDirectorPromptsMessages,
} from './buildPrompt.js';

export {
  buildDirectorMvImagePreviewClips,
  buildDirectorMvVideoPreviewClips,
  replaceDirectorMvPlaceholdersWithVideos,
  buildMvShotsIntentText,
  estimateShotCountFromMusicDuration,
  resolveDirectorMvAudioClipCount,
  planMvShotDurations,
  planMvShotDurationsForCount,
  distributeShotDurations,
  sumDirectorShotsDurationSec,
  ensureMvShotsMatchMusicDuration,
  ensureMvShotsCoverSceneNames,
  type DirectorMvTimelineClip,
} from './mvHelpers.js';

export {
  DIRECTOR_STYLE_PRESETS,
  getDirectorStylePreset,
  resolveDirectorStylePrompt,
  resolveDirectorStyleReferenceImageUrl,
  directorStylePresetImageUrl,
  normalizeDirectorStylePresetId,
  isDirectorStylePresetId,
  type DirectorStylePresetId,
  type DirectorStylePreset,
} from './stylePresets.js';

export {
  DIRECTOR_CAST_ARTWORK_PRESETS,
  directorCastArtworkImageUrl,
  getDirectorCastArtworkPreset,
  type DirectorCastArtworkPreset,
} from './castPresets.js';

export {
  composeDirectorShotFinalPrompt,
  composeDirectorShotStoryboardPrompt,
  composeDirectorShotVideoPrompt,
  extractDirectorSubjectMotion,
  appendDirectorCinematicLensToPrompt,
  ensureDirectorLipsyncMouthVisiblePrompt,
  stripDirectorDialogueFromPrompt,
  shouldAutoSyncDirectorFinalPrompt,
  canRecomposeDirectorFinalPrompt,
  withComposedDirectorFinalPrompts,
  DIRECTOR_STYLE_ON_CAST_AND_SCENE_GUARD,
  DIRECTOR_STYLE_REF_IMAGE_LOCK_GUARD,
  DIRECTOR_MONOCHROME_STYLE_LOCK_GUARD,
  directorStyleLooksMonochrome,
  DIRECTOR_LIPSYNC_MOUTH_VISIBLE_GUARD,
  DIRECTOR_LIPSYNC_SINGING_FRONT,
} from './composeFinalPrompt.js';

export {
  DIRECTOR_REVISE_FINAL_PROMPT_SYSTEM,
  buildDirectorReviseFinalPromptMessages,
  parseDirectorRevisedFinalPrompt,
  type DirectorReviseFinalPromptContext,
} from './reviseFinalPrompt.js';

export {
  DIRECTOR_CINEMATIC_CAMERA_GUIDE,
  DIRECTOR_CINEMATIC_PLOT_EXAMPLE_ROWS,
  DIRECTOR_CINEMATIC_PLOT_EXAMPLE_ROWS_CLOSE_UP,
  DIRECTOR_CINEMATIC_TECHNIQUE_INVENTORY,
  DIRECTOR_MV_PERFORMANCE_DYNAMICS_GUIDE,
  DIRECTOR_MV_SCENE_PROMPT_FORMULA_GUIDE,
  DIRECTOR_MV_CLOSE_UP_FRAMING_ON_GUIDE,
  DIRECTOR_MV_CLOSE_UP_FRAMING_OFF_GUIDE,
  composeDirectorCinematicLensPromptBlock,
  expandCinematicAngle,
  expandCinematicFocal,
  expandCinematicCameraMove,
  expandCinematicShotSize,
  pickCinematicAngleFallback,
  pickCinematicFocalFallback,
  resolveDirectorMvCloseUpFramingGuide,
  resolveDirectorMvPlotExampleRows,
} from './cinematicCameraLanguage.js';

export {
  DIRECTOR_MV_PLOT_BEAT_HEADER,
  parseDirectorMvPlotBeatTable,
  formatDirectorMvPlotBeatTable,
  countDirectorMvPlotBeatsWithCast,
  mapDirectorMvShotIndexToPlotBeat,
  alignDirectorMvPlotBeatsToCount,
  alignDirectorMvScriptSectionsToClipCount,
  inferDirectorMvShotFramingFromBeat,
  composeDirectorMvShotDescFromBeat,
  applyDirectorMvPlotBeatsToShots,
  getDirectorMvPlotBeatsFromState,
  resolveDirectorMvBeatCastLabel,
  type DirectorMvPlotBeatRow,
} from './plotBeatSheet.js';

export {
  coerceAssistantText,
  extractJsonObject,
  normalizeDirectorShotsResult,
  normalizeDirectorAssetsResult,
  normalizeDirectorPromptsResult,
  normalizeDirectorMvStoryAnalyzeResult,
  normalizeDirectorMvScriptResult,
  type NormalizeDirectorShotsResult,
  type NormalizeDirectorAssetsResult,
  type NormalizeDirectorPromptsResult,
  type NormalizeDirectorMvStoryAnalyzeResult,
  type NormalizeDirectorMvScriptResult,
} from './normalize.js';

export {
  DIRECTOR_SCENE_BUILTIN_SUFFIX,
  DIRECTOR_SCENE_UNIVERSAL_PROMPT,
  DIRECTOR_SCENE_NINE_GRID_LINKED_PROMPT,
  DIRECTOR_SCENE_NINE_GRID_ENGLISH,
  DIRECTOR_SCENE_360_PROMPT_TEMPLATE,
  DIRECTOR_360_EQUIRECTANGULAR_PROMPT_TEMPLATE,
  DIRECTOR_CHARACTER_LINKED_PROMPT,
  DIRECTOR_CHARACTER_LINKED_PROMPT_TEMPLATE,
  DIRECTOR_CHARACTER_FOUR_GRID_ENGLISH,
  sanitizeDirectorStyleHintForCharacter,
  ensureDirectorSceneBuiltinPrompt,
  buildDirectorSceneImagePrompt,
  buildDirector360EquirectangularPrompt,
  buildDirectorCharacterImagePrompt,
  buildDirectorPropImagePrompt,
  directorAssetAspectRatio,
} from './assetImagePrompts.js';

export {
  applyDirectorShotsPatch,
  applyDirectorAssetsPatch,
  applyDirectorPromptsPatch,
  updateDirectorShotCell,
  addDirectorShot,
  removeDirectorShot,
  insertDirectorShot,
  reorderDirectorShot,
  setDirectorPhase,
  setDirectorMode,
  patchDirectorMvMusic,
  patchDirectorMvStoryAnalysis,
  patchDirectorMvScriptInput,
  setDirectorMvCloseUpFraming,
  patchDirectorMvCastPlan,
  setDirectorMvAspectRatio,
  updateDirectorAsset,
  removeDirectorAsset,
  setDirectorAssetsStep,
  setSelectedDirectorAssetIds,
  getOrderedAssetsWithImages,
  updateDirectorShotStoryboard,
} from './statePatch.js';

export {
  bindDirectorShotAssetRefs,
  bindDirectorShotsAssetRefs,
  applyDirectorShotAssetBindingIndices,
  MAX_DIRECTOR_CHARACTER_IMAGE_REFS,
  matchDirectorAssetIndicesForShot,
  matchDirectorShotsAssetIndices,
  shotSuggestsNoCharacterRefs,
  shotSuggestsPersonPresent,
  shotDescriptionSuggestsEmptyCast,
  buildDirectorShotAssetHintLines,
  rebindDirectorPipelineAssetRefs,
  inferDirectorAssetGender,
  formatDirectorImageBindingClause,
  directorAssetKindLabel,
} from './bindAssetRefs.js';
