/**
 * Shared director pipeline (script + MV modes).
 */

export {
  SCHEMA_VERSION,
  SCRIPT_NODE_TYPE,
  DIRECTOR_NODE_TYPE,
  DIRECTOR_SHOT_COLUMNS,
  DIRECTOR_MV_ASPECT_OPTIONS,
  createEmptyDirectorShot,
  isBlankDirectorShot,
  createEmptyDirectorAsset,
  createEmptyDirectorAssets,
  createEmptyDirectorShotStoryboard,
  createEmptyDirectorMvMusic,
  DEFAULT_MV_CREDIT_NAME,
  resolveDirectorMvCreditName,
  createEmptyDirectorMvStoryAnalysis,
  createEmptyDirectorMvScriptSections,
  createEmptyDirectorMvCastPlan,
  createDefaultDirectorPipelineState,
  directorAssetBagKey,
  flattenDirectorAssets,
  findDirectorAssetById,
  countAssetsMissingImages,
  countAssetsWithImages,
  countShotsWithFinalPrompt,
  countDirectorStoryboards,
  countDirectorShotsWithDialogue,
  getDirectorShotStoryboard,
  directorDramaStoryboardKey,
  resolveDirectorStoryboardStorageKey,
  migrateBareDirectorStoryboardsToEpisode,
  listDirectorShotStoryboardImages,
  listDirectorShotVideos,
  directorMediaUrlKey,
  isDirectorLocalMediaUrl,
  isDirectorShotVideoSelection,
  mergeDirectorShotVideoHistory,
  replaceDirectorShotVideoUrlInPlace,
  getDirectorShotPromptVersions,
  bumpDirectorScriptContentRevision,
  isDirectorShotPromptsStale,
  countDirectorStalePromptShots,
  markAllDirectorShotsPromptsSynced,
  markDirectorShotPromptsSynced,
  normalizeDirectorStoryboardsByShotNo,
  getValidDirectorShotSongClipUrl,
  recommendDirectorShotLipsync,
  resolveDirectorShotPreferLipsync,
  evaluateDirectorShotLipsync,
  shotDescriptionSuggestsVisibleFace,
  shotDescriptionSuggestsCloseUpFace,
  shotHasCompleteLyricForLipsync,
  shotSuggestsClimax,
  computeDirectorShotMusicRanges,
  computeDirectorShotMusicRangesFromState,
  findDirectorShotRowIndex,
  resolveDirectorShotMusicRange,
  applyLyricPacksToDirectorShots,
  syncDirectorShotsToLyricTimeline,
  parseLrcToLyricSegments,
  normalizeDirectorMvLyricSegments,
  coverSongWithLyricSegments,
  calibrateLyricSegmentsWithUserLyrics,
  splitUserLyricLines,
  packLyricSegmentsIntoShotPacks,
  pickNearestMvClipDurationTier,
  DIRECTOR_MV_CLIP_DURATION_TIERS,
  DIRECTOR_MV_CLIP_DURATION_TIERS_LONG,
  DIRECTOR_MV_CLIP_DURATION_TIERS_SHORT,
  resolveMvClipDurationTiers,
  shotMusicRangesFromLyricPacks,
  shotAudioRangeHasHumanVoice,
  classifyDirectorMvPackAudioRole,
  directorMvPackAudioRoleLabelZh,
  isDirectorLyricShotPackInstrumental,
  applyDirectorInstrumentalVisualGuards,
  stripDirectorSingingPerformanceFromText,
  DIRECTOR_INSTRUMENTAL_NO_SING_GUARD,
  DIRECTOR_EMPTY_SHOT_FRONT_BANNER,
  DIRECTOR_EMPTY_SHOT_NEGATIVE_LINE,
  DIRECTOR_EMPTY_SHOT_NEGATIVE_PROMPT,
  DIRECTOR_MV_SCENE_NEGATIVE_PROMPT,
  DIRECTOR_EMPTY_SHOT_BEAT_LOCK,
  DIRECTOR_EMPTY_SHOT_NO_PEOPLE_GUARD,
  DIRECTOR_INSTRUMENTAL_EMPTY_SHOT_GUARD,
  isDirectorInstrumentalLyricText,
  sanitizeDirectorLyricDisplayText,
  isDirectorNonLyricMetaText,
  stripDirectorLyricsScriptMeta,
  breakDirectorLyricTextIntoLines,
  formatDirectorLyricsFromAsr,
  coerceDirectorMvAspectRatio,
  normalizeDirectorMvMusic,
  normalizeDirectorMvStoryAnalysis,
  normalizeDirectorMvScriptSections,
  normalizeDirectorMvCastPlan,
  parseDirectorMvScriptSectionsFromText,
  parseDirectorMvCharacterEntries,
  getDirectorMvCharactersSectionText,
  syncDirectorMvCastFromScript,
  ensureDirectorMvLeadSlots,
  listDirectorMvLeadAssetIds,
  inferDirectorMvCastPlanFromStory,
  applyAutoDirectorMvCastPlan,
  fillDirectorMvCastFromStoryRoles,
  parseDirectorMvOutlineRoleEntries,
  getDirectorMvLeadRolesFromStory,
  isDirectorMvCastPlanUserLocked,
  directorMvCastPlanComboId,
  applyDirectorMvCastPlan,
  formatDirectorMvLockedCastForPrompt,
  formatDirectorMvLockedCastForStoryPrompt,
  extractDirectorMvReferencePersonNames,
  directorMvLeadGenderLabelZh,
  directorMvLeadSeedPrompt,
  isDirectorMvLeadPromptWeak,
  inferDirectorMvLeadGenderFromText,
  parseDirectorMvSceneEntries,
  getDirectorMvScenesSectionText,
  syncDirectorMvScenesFromScript,
  directorMvScriptSectionsHaveContent,
  composeDirectorMvScriptText,
  parseDirectorShotDurationSec,
  normalizeDirectorMode,
  normalizeDirectorPhase,
  normalizeDirectorImageResolution,
  DRAMA_PHASES,
  MV_PHASES,
  type DirectorMode,
  type DirectorPhase,
  type DirectorAssetsStep,
  type DirectorShotColumnKey,
  type DirectorShot,
  type DirectorAssetKind,
  type DirectorAssetStatus,
  type DirectorAsset,
  type DirectorAssetsBag,
  type DirectorPipelineState,
  type DirectorShotStoryboard,
  type DirectorShotMusicRange,
  type DirectorStoryboardStatus,
  type DirectorMvMusic,
  type DirectorMvLyricSegment,
  type DirectorMvLyricSegmentStatus,
  type DirectorLyricShotPack,
  type DirectorMvPackAudioRole,
  type DirectorMvStoryAnalysis,
  type DirectorMvScriptSections,
  type DirectorMvCharacterEntry,
  type DirectorMvCastPlan,
  type DirectorMvCastPlanComboId,
  type DirectorMvLeadGender,
  type DirectorAssetGender,
  type DirectorMvAspectRatio,
  type SyncDirectorMvCastMode,
  type DirectorLipsyncPriority,
  type DirectorLipsyncRecommendation,
} from './schema.js';

export {
  DIRECTOR_SHOTS_SYSTEM_PROMPT,
  DIRECTOR_SHOTS_USER_PROMPT_TEMPLATE,
  DIRECTOR_MV_SHOTS_SYSTEM_PROMPT,
  DIRECTOR_MV_SHOTS_USER_PROMPT_TEMPLATE,
  DIRECTOR_MV_STORY_ANALYZE_SYSTEM_PROMPT,
  DIRECTOR_MV_STORY_ANALYZE_USER_PROMPT_TEMPLATE,
  DIRECTOR_MV_STORY_OUTLINE_SYSTEM_PROMPT,
  DIRECTOR_MV_STORY_OUTLINE_USER_PROMPT_TEMPLATE,
  DIRECTOR_MV_SCRIPT_SYSTEM_PROMPT,
  DIRECTOR_MV_SCRIPT_USER_PROMPT_TEMPLATE,
  DIRECTOR_DRAMA_SCRIPT_SYSTEM_PROMPT,
  DIRECTOR_DRAMA_SCRIPT_USER_PROMPT_TEMPLATE,
  DIRECTOR_ASSETS_SYSTEM_PROMPT,
  DIRECTOR_ASSETS_USER_PROMPT_TEMPLATE,
  DIRECTOR_PROMPTS_SYSTEM_PROMPT,
  DIRECTOR_PROMPTS_USER_PROMPT_TEMPLATE,
} from './prompts.js';

export {
  fillTemplate,
  buildDirectorShotsMessages,
  buildDirectorMvShotsMessages,
  buildDirectorMvStoryAnalyzeMessages,
  buildDirectorMvStoryOutlineMessages,
  buildDirectorMvScriptMessages,
  buildDirectorMvScriptPlotContinueMessages,
  buildDirectorDramaScriptMessages,
  buildDirectorAssetsMessages,
  buildDirectorPromptsMessages,
} from './buildPrompt.js';

export {
  DIRECTOR_DRAMA_DEFAULT_SHOT_COUNT,
  ensureDirectorDramaShotsFromScript,
  applyDirectorDramaScriptResult,
  completeDirectorDramaShotLayers,
} from './dramaHelpers.js';

export {
  buildDirectorMvImagePreviewClips,
  buildDirectorMvVideoPreviewClips,
  buildDirectorDramaSequentialVideoClips,
  replaceDirectorMvPlaceholdersWithVideos,
  buildMvShotsIntentText,
  estimateShotCountFromMusicDuration,
  resolveDirectorMvAudioClipCount,
  planMvShotDurations,
  planMvShotDurationsForCount,
  distributeShotDurations,
  sumDirectorShotsDurationSec,
  ensureMvShotsMatchMusicDuration,
  ensureMvShotsCoverSceneNames,
  normalizeDirectorShotNoKey,
  type DirectorMvTimelineClip,
} from './mvHelpers.js';

export {
  DIRECTOR_STYLE_PRESETS,
  getDirectorStylePreset,
  resolveDirectorStylePrompt,
  resolveDirectorStylePictureLabel,
  formatDirectorStyleFromRefImageHint,
  resolveDirectorStyleReferenceImageUrl,
  directorStylePresetImageUrl,
  normalizeDirectorStylePresetId,
  isDirectorStylePresetId,
  type DirectorStylePresetId,
  type DirectorStylePreset,
} from './stylePresets.js';

export {
  DIRECTOR_CAST_ARTWORK_PRESETS,
  directorCastArtworkImageUrl,
  getDirectorCastArtworkPreset,
  type DirectorCastArtworkPreset,
} from './castPresets.js';

export {
  composeDirectorShotFinalPrompt,
  composeDirectorShotStoryboardPrompt,
  composeDirectorShotVideoPrompt,
  resolveDirectorShotVideoPromptForGen,
  extractDirectorSubjectMotion,
  appendDirectorCinematicLensToPrompt,
  ensureDirectorLipsyncMouthVisiblePrompt,
  ensureDirectorNoLipsyncMouthClosedPrompt,
  ensureDirectorMvNoOnscreenTextPrompt,
  ensureDirectorMvVideoPromptGuards,
  adaptDirectorPromptForLtxI2v,
  ensureDirectorDramaVideoPromptGuards,
  isDramaH3ZhNaturalApiPrompt,
  applyDirectorLipsyncToggleToFinalPrompt,
  stripDirectorDialogueFromPrompt,
  stripDirectorMouthOpenPerformanceFromText,
  shouldAutoSyncDirectorFinalPrompt,
  canRecomposeDirectorFinalPrompt,
  withComposedDirectorFinalPrompts,
  isDirectorH3ZhSixSectionPrompt,
  stripDirectorH3DialogueTags,
  stripChineseOutsideH3DialogueTags,
  DIRECTOR_STYLE_FROM_REF_IMAGE_HINT,
  replaceDirectorStyleTextWithImageRef,
  DIRECTOR_STYLE_ON_CAST_AND_SCENE_GUARD,
  DIRECTOR_STYLE_REF_IMAGE_LOCK_GUARD,
  DIRECTOR_MONOCHROME_STYLE_LOCK_GUARD,
  directorStyleLooksMonochrome,
  DIRECTOR_MV_NO_ONSCREEN_TEXT_GUARD,
  DIRECTOR_DRAMA_SOUNDSCAPE_GUARD,
  DIRECTOR_DRAMA_NO_SUBTITLE_GUARD,
  DIRECTOR_LIPSYNC_MOUTH_VISIBLE_GUARD,
  DIRECTOR_LIPSYNC_SINGING_FRONT,
  DIRECTOR_LIPSYNC_EXTRAS_MOUTH_CLOSED_GUARD,
  DIRECTOR_NO_LIPSYNC_MOUTH_CLOSED_GUARD,
  DIRECTOR_NO_LIPSYNC_SILENT_FRONT,
} from './composeFinalPrompt.js';

export {
  DIRECTOR_REVISE_FINAL_PROMPT_SYSTEM,
  buildDirectorReviseFinalPromptMessages,
  parseDirectorRevisedFinalPrompt,
  isDirectorFinalPromptFullRewriteOpinion,
  type DirectorReviseFinalPromptContext,
} from './reviseFinalPrompt.js';

export {
  DIRECTOR_REVISE_DRAMA_CUT_SYSTEM,
  DIRECTOR_REVISE_DRAMA_CUT_BATCH_SYSTEM,
  buildDirectorReviseDramaCutMessages,
  buildDirectorReviseDramaCutBatchMessages,
  parseDirectorRevisedDramaCut,
  parseDirectorRevisedDramaCutBatch,
  type DramaCutReviseContext,
  type DramaCutReviseResult,
} from './reviseDramaCutPrompt.js';

export {
  DIRECTOR_CINEMATIC_CAMERA_GUIDE,
  DIRECTOR_CINEMATIC_PLOT_EXAMPLE_ROWS,
  DIRECTOR_CINEMATIC_PLOT_EXAMPLE_ROWS_CLOSE_UP,
  DIRECTOR_CINEMATIC_TECHNIQUE_INVENTORY,
  DIRECTOR_MV_PERFORMANCE_DYNAMICS_GUIDE,
  DIRECTOR_MV_SCENE_PROMPT_FORMULA_GUIDE,
  DIRECTOR_MV_CLOSE_UP_FRAMING_ON_GUIDE,
  DIRECTOR_MV_CLOSE_UP_FRAMING_OFF_GUIDE,
  DIRECTOR_MV_H3_ZH_PROMPT_FORMAT_GUIDE,
  DIRECTOR_MV_SHOT_CHANGE_PACE_PRESETS,
  composeDirectorCinematicLensPromptBlock,
  expandCinematicAngle,
  expandCinematicFocal,
  expandCinematicCameraMove,
  expandCinematicShotSize,
  pickCinematicAngleFallback,
  pickCinematicFocalFallback,
  resolveDirectorMvCloseUpFramingGuide,
  resolveDirectorMvPlotExampleRows,
  resolveDirectorMvShotChangePaceGuide,
  getDirectorMvShotChangePacePreset,
  normalizeDirectorMvShotChangePace,
  type DirectorMvShotChangePace,
  type DirectorMvShotChangePacePreset,
} from './cinematicCameraLanguage.js';

export {
  DIRECTOR_MV_STORY_GENRE_TYPES,
  DIRECTOR_MV_STORY_TONE_STYLES,
  DIRECTOR_MV_STORY_ENDING_TYPES,
  formatDirectorMvStoryPrefsForPrompt,
  applyDirectorMvStoryPrefsToOutline,
  normalizeDirectorMvStoryGenreType,
  normalizeDirectorMvStoryToneStyle,
  normalizeDirectorMvStoryEndingType,
  type DirectorMvStoryGenreType,
  type DirectorMvStoryToneStyle,
  type DirectorMvStoryEndingType,
} from './mvStoryPrefs.js';

export {
  DIRECTOR_MV_PLOT_BEAT_HEADER,
  parseDirectorMvPlotBeatTable,
  formatDirectorMvPlotBeatTable,
  coerceDirectorMvPlotToBeatTable,
  countDirectorMvPlotBeatsWithCast,
  mapDirectorMvShotIndexToPlotBeat,
  alignDirectorMvPlotBeatsToCount,
  alignDirectorMvScriptSectionsToClipCount,
  inferDirectorMvShotFramingFromBeat,
  composeDirectorMvShotDescFromBeat,
  applyDirectorMvPlotBeatToOneShot,
  applyDirectorMvPlotBeatsToShots,
  getDirectorMvPlotBeatsFromState,
  resolveDirectorMvBeatCastLabel,
  type DirectorMvPlotBeatRow,
} from './plotBeatSheet.js';

export {
  coerceAssistantText,
  extractJsonObject,
  normalizeDirectorShotsResult,
  normalizeDirectorAssetsResult,
  normalizeDirectorPromptsResult,
  normalizeDirectorMvStoryAnalyzeResult,
  normalizeDirectorMvScriptResult,
  normalizeDirectorMvStoryOutlineResult,
  type NormalizeDirectorShotsResult,
  type NormalizeDirectorAssetsResult,
  type NormalizeDirectorPromptsResult,
  type NormalizeDirectorMvStoryAnalyzeResult,
  type NormalizeDirectorMvScriptResult,
} from './normalize.js';

export {
  DIRECTOR_SCENE_BUILTIN_SUFFIX,
  DIRECTOR_SCENE_UNIVERSAL_PROMPT,
  DIRECTOR_SCENE_NINE_GRID_LINKED_PROMPT,
  DIRECTOR_SCENE_SINGLE_ENGLISH,
  DIRECTOR_SCENE_NINE_GRID_ENGLISH,
  DIRECTOR_SCENE_360_PROMPT_TEMPLATE,
  DIRECTOR_360_EQUIRECTANGULAR_PROMPT_TEMPLATE,
  DIRECTOR_CHARACTER_LINKED_PROMPT,
  DIRECTOR_CHARACTER_LINKED_PROMPT_TEMPLATE,
  DIRECTOR_CHARACTER_FOUR_GRID_ENGLISH,
  sanitizeDirectorStyleHintForCharacter,
  ensureDirectorSceneBuiltinPrompt,
  buildDirectorSceneImagePrompt,
  buildDirector360EquirectangularPrompt,
  buildDirectorCharacterImagePrompt,
  buildDirectorPropImagePrompt,
  buildDirectorSystemVisualImagePrompt,
  DIRECTOR_SYSTEM_VISUAL_LINKED_PROMPT,
  DIRECTOR_SYSTEM_VISUAL_FOUR_GRID_ENGLISH,
  directorAssetAspectRatio,
} from './assetImagePrompts.js';

export {
  applyDirectorShotsPatch,
  applyDirectorAssetsPatch,
  applyDirectorPromptsPatch,
  updateDirectorShotCell,
  addDirectorShot,
  removeDirectorShot,
  insertDirectorShot,
  reorderDirectorShot,
  remapDramaStoryboardsAfterShotListEdit,
  setDirectorPhase,
  setDirectorMode,
  patchDirectorMvMusic,
  patchDirectorMvStoryAnalysis,
  patchDirectorMvScriptInput,
  setDirectorMvCloseUpFraming,
  patchDirectorMvCastPlan,
  setDirectorMvAspectRatio,
  updateDirectorAsset,
  upsertDirectorAsset,
  removeDirectorAsset,
  setDirectorAssetsStep,
  setSelectedDirectorAssetIds,
  getOrderedAssetsWithImages,
  updateDirectorShotStoryboard,
  mergeDirectorMediaPreserve,
} from './statePatch.js';

export {
  bindDirectorShotAssetRefs,
  bindDirectorShotsAssetRefs,
  applyDirectorShotAssetBindingIndices,
  MAX_DIRECTOR_CHARACTER_IMAGE_REFS,
  matchDirectorAssetIndicesForShot,
  resolveDirectorShotCastAssetIds,
  matchDirectorShotsAssetIndices,
  shotSuggestsNoCharacterRefs,
  shotSuggestsPersonPresent,
  shotDescriptionSuggestsEmptyCast,
  buildDirectorShotAssetHintLines,
  rebindDirectorPipelineAssetRefs,
  inferDirectorAssetGender,
  formatDirectorImageBindingClause,
  formatDirectorShotRefBindingClause,
  directorAssetKindLabel,
  buildDirectorShotRefItems,
  resolveDirectorShotRefItems,
  parseDirectorShotRefBindings,
  annotateDirectorPromptRefNumbers,
  clarifyDirectorPromptRefPictureNumbers,
  repairDirectorMvPromptImageMap,
  stripDirectorPromptInventedLook,
  directorMvPromptNeedsLookRelock,
  isDirectorEmptyShotPrompt,
  insertDirectorPromptAfterLookHead,
  DIRECTOR_PIC1_COLOR_FRONT,
  DIRECTOR_PIC1_VISUAL_ANCHOR,
  DIRECTOR_PIC1_LOOK_NEGATIVE_LINE,
  buildDirectorShotSceneStoryHint,
} from './bindAssetRefs.js';

export {
  applyDirectorMvStaleScriptUpdateToShot,
  applyDirectorMvStaleScriptUpdateToAllStaleShots,
  rebuildDirectorShotPromptFromScript,
  rebuildDirectorAllShotPromptsFromScript,
} from './scriptPromptSync.js';

export {
  composeMinimaxH3ChineseOfficialRefPrompt,
  buildMinimaxH3ZhRefImageSlots,
  composeDirectorH3ZhDetailedTimeline,
  formatDirectorH3Timecode,
  formatDirectorH3TimeRange,
  buildDirectorH3BeatEdges,
  type MinimaxH3ZhRefImageSlot,
} from './minimaxH3DramaPrompt.js';
