export type {
  KaraokeAssAlignment,
  KaraokeAsrLanguage,
  KaraokeAsrWordTiming,
  KaraokeAudioSource,
  KaraokeCharTiming,
  KaraokeCountdownOptions,
  KaraokeCountdownPlan,
  KaraokeCountdownWindow,
  KaraokeIndicatorOptions,
  KaraokeLayoutMode,
  KaraokeLine,
  KaraokeLineTimingQuality,
  KaraokeOpeningTimeline,
  KaraokePos,
  KaraokePositionPreset,
  KaraokeProject,
  KaraokeReentryTimeline,
  KaraokeRole,
  KaraokeRoleColors,
  KaraokeStyleOptions,
  KaraokeStyleResolved,
  KaraokeTimingSource,
} from './types.js';
export {
  ASS_PLAY_RES_X,
  ASS_PLAY_RES_Y,
  ASS_KARAOKE_RENDER_SCALE,
  assBgrToCssHex,
  assColorTag,
  clampKaraokeAssAlignment,
  clampKaraokeCountdownLeadInMaxSec,
  clampKaraokeCountdownReentryGapSec,
  clampKaraokeInterludeClearGapSec,
  clampKaraokeLineFadeOutSec,
  clampKaraokeOpeningCreditFontSize,
  clampKaraokeOpeningTitleFontSize,
  clampKaraokeOutline,
  clampKaraokeShadow,
  clampKaraokePos,
  cssHexToAssBgr,
  normalizeKaraokeAssColor,
  DEFAULT_KARAOKE_COUNTDOWN,
  DEFAULT_KARAOKE_COUNTDOWN_ANCHOR,
  DEFAULT_KARAOKE_CREDIT_NAME,
  DEFAULT_KARAOKE_INDICATOR,
  DEFAULT_KARAOKE_POS_A,
  DEFAULT_KARAOKE_POS_B,
  DEFAULT_KARAOKE_POS_SINGLE,
  DEFAULT_KARAOKE_STYLE,
  DEFAULT_KARAOKE_OPENING_TITLE_POS,
  createDefaultKaraokeStyle,
  KARAOKE_ASR_LANGUAGE_OPTIONS,
  KARAOKE_FALLBACK_FONT,
  KARAOKE_FONT_PRESETS,
  KARAOKE_COUNTDOWN_DOT_SIZE_DEFAULT,
  KARAOKE_COUNTDOWN_DOT_SIZE_MAX,
  KARAOKE_COUNTDOWN_DOT_SIZE_MIN,
  KARAOKE_COUNTDOWN_LEAD_IN_MAX_SEC_MAX,
  KARAOKE_COUNTDOWN_LEAD_IN_MAX_SEC_MIN,
  KARAOKE_COUNTDOWN_POSITIONS_MAX,
  KARAOKE_COUNTDOWN_REENTRY_GAP_SEC,
  KARAOKE_COUNTDOWN_REENTRY_GAP_SEC_MAX,
  KARAOKE_COUNTDOWN_REENTRY_GAP_SEC_MIN,
  KARAOKE_COUNTDOWN_SPACING_DEFAULT,
  KARAOKE_COUNTDOWN_SPACING_MAX,
  KARAOKE_COUNTDOWN_SPACING_MIN,
  KARAOKE_INTERLUDE_CLEAR_GAP_SEC_MAX,
  KARAOKE_INTERLUDE_CLEAR_GAP_SEC_MIN,
  KARAOKE_INTERLUDE_GAP_SEC,
  KARAOKE_MAX_COUNTDOWN_REENTRY,
  KARAOKE_LINE_FADE_OUT_SEC,
  KARAOKE_LINE_FADE_OUT_SEC_MAX,
  KARAOKE_LINE_FADE_OUT_SEC_MIN,
  KARAOKE_LYRIC_OUTLINE_DEFAULT,
  KARAOKE_LYRIC_SUNG_OUTLINE_DEFAULT,
  KARAOKE_LYRIC_OUTLINE_LEGACY_DEFAULT,
  KARAOKE_LYRIC_SHADOW_DEFAULT,
  KARAOKE_SHADOW_MAX,
  KARAOKE_SHADOW_MIN,
  KARAOKE_SUNG_OUTLINE_COLOR_LEGACY,
  karaokeLyricStrokeLegacyPatch,
  KARAOKE_OPENING_COMPOSER_POS,
  KARAOKE_OPENING_COUNTDOWN_COUNT,
  KARAOKE_OPENING_COUNTDOWN_DOT_FADE_SEC,
  KARAOKE_OPENING_COUNTDOWN_HOLD_SEC,
  KARAOKE_OPENING_COUNTDOWN_INTERVAL_SEC,
  KARAOKE_OPENING_COUNTDOWN_MAX_SEC,
  KARAOKE_OPENING_COUNTDOWN_OFFSET_Y,
  KARAOKE_OPENING_CREDIT_FONT_SIZE,
  KARAOKE_OPENING_CREDIT_FONT_SIZE_MAX,
  KARAOKE_OPENING_CREDIT_FONT_SIZE_MIN,
  KARAOKE_OPENING_CREDIT_OUTLINE,
  KARAOKE_OPENING_FADE_OUT_SEC,
  KARAOKE_OPENING_FALLBACK_SEC,
  KARAOKE_OPENING_LYRICIST_POS,
  KARAOKE_OPENING_OUTLINE_ASS,
  KARAOKE_OPENING_OUTLINE_CSS,
  KARAOKE_OPENING_PRIMARY_ASS,
  KARAOKE_OPENING_PRIMARY_CSS,
  KARAOKE_OPENING_TITLE_FONT_SIZE,
  KARAOKE_OPENING_TITLE_FONT_SIZE_MAX,
  KARAOKE_OPENING_TITLE_FONT_SIZE_MIN,
  KARAOKE_OPENING_TITLE_OUTLINE,
  KARAOKE_OPENING_TITLE_Y,
  KARAOKE_OUTLINE_MAX,
  KARAOKE_OUTLINE_MIN,
  KARAOKE_PREFERRED_FONT,
  KARAOKE_PREFERRED_FONT_LEGACY,
  KARAOKE_ROLE_SUNG_COLORS,
  isLegacyCenteredKaraokeDualPos,
  isLegacyEdgeKaraokeDualPos,
  isKaraokeDualDefaultPosA,
  shouldMigrateKaraokeDualPosToDefault,
  shouldMigrateKaraokeSinglePosToDefault,
  karaokeAlignmentFromPreset,
  karaokeAsrLanguageToApiParam,
  karaokeClampAppearAfterInterludes,
  karaokeCountdownDefaultDotPos,
  karaokeCountdownDotOpacity,
  karaokeCountdownGroupAnchor,
  karaokeCountdownLitDots,
  karaokeCountdownPlanFromAvailable,
  karaokeCountdownResolvedDotPos,
  karaokeCountdownWindowLitDots,
  karaokeCountdownWindowStartSec,
  clampKaraokeCountdownAnchor,
  clampKaraokeCountdownSpacing,
  karaokeDualPosFromPreset,
  karaokeIsInterludeGap,
  karaokeLineCompressedFadeSec,
  karaokeLineDisplayAppearSec,
  karaokeLineFadeOutOpacity,
  karaokeLineSameSlotAppearSec,
  karaokeLineVisibleEndSec,
  karaokeMarginAlignmentFromPos,
  karaokeOpeningCountdownAnchorPos,
  karaokeOpeningCountdownLitDots,
  karaokeOpeningLeadInDurSec,
  karaokeOpeningTimeline,
  karaokePosFromMarginAlignment,
  karaokePosFromPreset,
  karaokePresetFromAlignment,
  karaokeReentryCountdownLitDots,
  karaokeReentryLeadInDurSec,
  karaokeReentryTimeline,
  karaokeSelectCountdownReentryLineIndexes,
  LEGACY_CENTERED_KARAOKE_POS_A,
  LEGACY_CENTERED_KARAOKE_POS_B,
  LEGACY_EDGE_KARAOKE_POS_A,
  LEGACY_EDGE_KARAOKE_POS_B,
  normalizeKaraokeAsrLanguage,
  resolveKaraokeAudioSource,
  resolveKaraokeCountdown,
  resolveKaraokeCountdownAnchor,
  resolveKaraokeCountdownPositions,
  resolveKaraokeCreditName,
  resolveKaraokeIndicator,
  resolveKaraokeInterludeTiming,
  resolveKaraokeLayoutMode,
  defaultKaraokePosAForLayout,
  resolveKaraokePosA,
  resolveKaraokePosB,
  resolveKaraokeOpeningTitlePos,
  resolveKaraokeOpeningLyricistPos,
  resolveKaraokeOpeningComposerPos,
  resolveKaraokeRoleColors,
} from './types.js';

export {
  looksLikeLrc,
  splitKaraokeUnits,
  interpolateCharsInLine,
  mapAsrWordsToLineChars,
  alignUserLyricLinesToAsrWords,
  flattenAsrWordsFromSegments,
  segmentToKaraokeLine,
  lyricSegmentsToKaraokeLines,
  expandOverlongKaraokeLine,
  prepareKaraokeLinesForRender,
  sanitizeKaraokeDisplayLines,
  applyGlobalOffsetToLines,
  retimelineKaraokeLine,
  applyCharTimingRipple,
  patchKaraokeLineCharTiming,
  remapKaraokeLineText,
  allocateInsertTiming,
  insertKaraokeLineChars,
  insertKaraokeCharPreservingTiming,
  deleteKaraokeLineChar,
  lyricsTextFromKaraokeLines,
  patchKaraokeLyricsForChangedLines,
  rescaleKaraokeLineTiming,
  buildKaraokeLinesFromAvailable,
  buildKaraokeLinesFromCalibratedSegments,
  countSingableChars,
  isInterpolatedKaraokeTiming,
  isWeakOrInterpolatedKaraokeLine,
  recomputeKaraokeWeakLineAlignment,
  projectHasWeakLineAlignment,
  MIN_CHAR_WIPE_SEC,
  INSERT_CHAR_DUR_MIN_SEC,
  INSERT_CHAR_DUR_MAX_SEC,
  INSERT_CHAR_DUR_IDEAL_SEC,
  karaokeCharsHaveWipeJumps,
} from './wordTiming.js';

export {
  annotateKaraokeLinesRoles,
  couldBeKaraokeRoleMarkerPrefix,
  extractSingableCharsSkippingRoleMarkers,
  displayKaraokeRoleMarker,
  formatKaraokeRoleMarker,
  formatKaraokeRoleMarkerColon,
  isKaraokeRoleMarker,
  karaokeRoleFromMarkerChar,
  karaokeLineLeadSungAss,
  karaokeLineLeadSungCss,
  karaokeRoleSungAss,
  karaokeRoleSungCss,
  karaokeTextHasRoleMarker,
  KARAOKE_ROLE_MARKER_RE,
  KARAOKE_ROLE_SUNG_ASS,
  KARAOKE_ROLE_SUNG_CSS,
  normalizeKaraokeLyricColons,
  normalizeKaraokeRoleMarkerUnit,
  normalizeKaraokeRoleMarkersInText,
  parseKaraokeRoleMarker,
  splitKaraokeUnitsKeepingRoles,
  stripKaraokeRoleMarkers,
  weaveKaraokeRoleChars,
} from './roleMarkers.js';

export {
  buildKaraokeAss,
  buildKaraokeCountdownDialogues,
  buildKaraokeCountdownPos,
  buildKaraokeCountdownWindowDialogues,
  buildKaraokeDialogueBaseCharText,
  buildKaraokeDialogueBaseRoleMarkersText,
  buildKaraokeDialogueBaseText,
  buildKaraokeDialogueText,
  buildKaraokeRoleMarkersOverlayText,
  buildKaraokeSungCharOverlayText,
  buildKaraokeSungCharHoldText,
  buildKaraokeSungCharWipeText,
  buildKaraokeSungOutlineWipeCharText,
  buildKaraokeWipeClipTags,
  buildKaraokeCharStaticClipTag,
  karaokeWipeClipRightPad,
  karaokeWipeClipSteps,
  karaokeWipeClipSpanPx,
  karaokeWipeSmoothDurationSec,
  karaokeCharWipeVisualEndSec,
  karaokeWipeDurMsFromAssTimes,
  karaokeAssCentiseconds,
  ensureAssDialogueEndSec,
  KARAOKE_WIPE_TARGET_FPS,
  KARAOKE_WIPE_MAX_SCALED_PX_PER_FRAME,
  KARAOKE_WIPE_MIN_FRAMES,
  KARAOKE_WIPE_MAX_STRETCH_SEC,
  type KaraokeWipeClipOptions,
  type KaraokeCharPlayResBox,
  buildKaraokeOpeningCountdownDialogues,
  buildKaraokeOpeningDialogues,
  buildKaraokePosOverride,
  buildKaraokeReentryCountdownDialogues,
  estimateAssTextWidth,
  fitKaraokeLineLayout,
  layoutKaraokeLineCharBoxes,
  karaokeLineSingEndSec,
  karaokeLineSingStartSec,
  karaokeOpeningEndSec,
  karaokeOpeningFadeOutSec,
  karaokeOpeningTimelineForProject,
  karaokeOutlineCornerBlur,
  karaokeOutlineSoftTag,
  karaokeAssBordWidth,
  karaokeLyricShadowDistance,
  karaokeSoftShadowDistanceBlur,
  karaokeSoftShadowBackColour,
  karaokeSungSoftShadowBlur,
  karaokeSungSoftTag,
  karaokeUnsungSoftShadowBlur,
  karaokeUnsungSoftTag,
  secToKCentis,
} from './buildAss.js';

export {
  buildRoundedTextOutlineShadow,
  buildKaraokeFixedLyricOutlineShadow,
  buildKaraokeSungOutlineShadow,
  karaokePreviewSoftGlowLayers,
  mergeKaraokePreviewStyle,
  singableLines,
  contentfulSingableLines,
  lineWipeWindow,
  findActiveSingableIndex,
  findFadingSingableLine,
  findNextSingableIndex,
  resolveDualSlotAtTime,
  resolveDualPreviewAtTime,
  resolveSinglePreviewAtTime,
  karaokeFirstLyricAppearSec,
  linePreviewChars,
  charWipeRatio,
  karaokeLineCharWipeVisualEnds,
  karaokeOpeningCaptureBusyUntilSec,
  karaokeCountdownWindowActiveAt,
  karaokeReentryCountdownWindowsForLines,
  karaokeCountdownOverlayNeedsUniqueFrame,
  karaokeOverlayNeedsUniqueFrame,
  karaokeSungWipeClipPathCss,
  karaokeSungWipeMaskStyles,
  activeCharProgress,
  type KaraokeSungWipeMaskStyles,
  openingCreditsOpacity,
  computePlayResPreviewLayout,
  fitPreviewLineLayout,
  resolveCountdownSlotAtTime,
  type DualSlotState,
  type DualPreviewState,
  type DualPreviewResolveOpts,
  type SinglePreviewState,
  type PreviewLineLayout,
} from './previewLogic.js';

export {
  karaokeProjectFromDirectorSource,
  karaokeProjectFromDirectorState,
  hasTrustedKaraokeLyricSegments,
  planKaraokeTiming,
  applyAsrSegmentsToKaraokeProject,
  karaokeAssFromProject,
  type KaraokeDirectorSource,
  type KaraokeTimingPlan,
  type AsrSegmentWithWords,
} from './fromDirector.js';

export {
  KARAOKE_EMBEDDED_FONTS,
  ensureKaraokeEmbeddedFonts,
  isKaraokeEmbeddedFontsReady,
  type KaraokeEmbeddedFont,
} from './embeddedFonts.js';

export {
  KARAOKE_CSS_BURN_DEFAULT_FPS,
  KARAOKE_CSS_BURN_LOW_SPEC_FPS,
  KARAOKE_CSS_BURN_SMOOTH_FPS,
  KARAOKE_CSS_BURN_MAX_FPS,
  KARAOKE_CSS_BURN_FAST_FPS,
  KARAOKE_CSS_BURN_STANDARD_FPS,
  KARAOKE_CSS_BURN_FLUID_FPS,
  KARAOKE_CSS_BURN_QUALITY_PRESET_IDS,
  isKaraokeCssBurnQualityPreset,
  karaokeCssBurnOptionsFromQualityPreset,
  defaultKaraokeCssBurnQualityPreset,
  karaokeCssBurnFrameTimeSec,
  normalizeKaraokeSourceFps,
  resolveKaraokeCssBurnFps,
  type KaraokeCssBurnQualityPreset,
} from './cssBurnTiming.js';
